- name: 设置 python 解释器
  set_fact:
    # Kylin需要开启(https://blog.csdn.net/yy4545/article/details/125652470)
    ansible_python_interpreter: /usr/bin/python3
  when: ansible_distribution is regex ("Kylin.*")

- name: 卸载相关软件
  yum:
    name:
    - kubeadm
    - kubectl
    - kubelet
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: absent